Repository DOSOPT-CDS-APP-TEAM5/Carrot-Server, pull requests merged in 2023-11, with the labels that each got.

#4 [FEAT] 엔티티 설계
  CarrotServer/.gitignore
  CarrotServer/build.gradle
  CarrotServer/src/main/java/CarrotServer/domain/Albums.java
  CarrotServer/src/main/java/CarrotServer/domain/ClubCategory.java
  CarrotServer/src/main/java/CarrotServer/domain/Clubs.java
  CarrotServer/src/main/java/CarrotServer/domain/LifeCategory.java
  CarrotServer/src/main/java/CarrotServer/domain/Lives.java
  CarrotServer/src/main/java/CarrotServer/domain/Profiles.java
  CarrotServer/src/main/java/CarrotServer/domain/d
Labels: euna, FEAT

#6 [SETTING] 공통 RESPONSE 클래스, Custom Error 생성 및 SWAGGER 설정 추가
  CarrotServer/build.gradle
  CarrotServer/src/main/java/CarrotServer/common/a
  CarrotServer/src/main/java/CarrotServer/common/response/ApiResponse.java
  CarrotServer/src/main/java/CarrotServer/common/swagger/SwaggerConfig.java
  CarrotServer/src/main/java/CarrotServer/exception/Error.java
  CarrotServer/src/main/java/CarrotServer/exception/Success.java
  CarrotServer/src/main/java/CarrotServer/exception/model/CarrotException.java
  CarrotServer/src/main/java/CarrotServer/exception/model/e
Labels: euna

#9 [FEAT] 엔티티 연관관계에 지연로딩 추가 및 동네 생활 "취미생활" 카테고리 추가 반영
  CarrotServer/src/main/java/CarrotServer/domain/Albums.java
  CarrotServer/src/main/java/CarrotServer/domain/LifeCategory.java
  CarrotServer/src/main/java/CarrotServer/domain/Profiles.java
Labels: euna, FEAT

#10 [FEAT] 우리동네 모임 상세조회 기능 추가
  CarrotServer/build.gradle
  CarrotServer/src/main/java/CarrotServer/controller/ClubController.java
  CarrotServer/src/main/java/CarrotServer/controller/response/AlbumGetResposne.java
  CarrotServer/src/main/java/CarrotServer/controller/response/ClubGetResponse.java
  CarrotServer/src/main/java/CarrotServer/controller/response/c
  CarrotServer/src/main/java/CarrotServer/domain/Albums.java
  CarrotServer/src/main/java/CarrotServer/domain/Clubs.java
  CarrotServer/src/main/java/CarrotServer/exception/Success.java
  CarrotServer/src/main/java/CarrotServer/repository/ClubJpaRepository.java
  CarrotServer/src/main/java/CarrotServer/repository/f
  CarrotServer/src/main/java/CarrotServer/service/ClubService.java
  CarrotServer/src/main/java/CarrotServer/service/g
Labels: FEAT, 2.or_kng

#13 [FEAT] 모임 프로필 생성 기능 추가
  CarrotServer/src/main/java/CarrotServer/controller/ClubController.java
  CarrotServer/src/main/java/CarrotServer/controller/request/ProfileCreateRequest.java
  CarrotServer/src/main/java/CarrotServer/controller/request/b
  CarrotServer/src/main/java/CarrotServer/domain/Profiles.java
  CarrotServer/src/main/java/CarrotServer/exception/Success.java
  CarrotServer/src/main/java/CarrotServer/repository/ProfileJpaRepository.java
  CarrotServer/src/main/java/CarrotServer/service/ProfileService.java
Labels: FEAT, 2.or_kng

#14 [FEAT] 동네 생활 리스트 조회 API 개발
  CarrotServer/build.gradle
  CarrotServer/src/main/java/CarrotServer/controller/LifeController.java
  CarrotServer/src/main/java/CarrotServer/controller/response/LifeListResponseDTO.java
  CarrotServer/src/main/java/CarrotServer/domain/LifeCategory.java
  CarrotServer/src/main/java/CarrotServer/exception/Error.java
  CarrotServer/src/main/java/CarrotServer/exception/Success.java
  CarrotServer/src/main/java/CarrotServer/mapper/LifeMapper.java
  CarrotServer/src/main/java/CarrotServer/repository/LifeJpaRepository.java
  CarrotServer/src/main/java/CarrotServer/service/LifeService.java
Labels: euna, FEAT

#16 [FEAT] 모임 더 둘러보기 API 개발
  CarrotServer/src/main/java/CarrotServer/common/enums/ClubCategory.java
  CarrotServer/src/main/java/CarrotServer/common/enums/LifeCategory.java
  CarrotServer/src/main/java/CarrotServer/controller/ClubController.java
  CarrotServer/src/main/java/CarrotServer/controller/LifeController.java
  CarrotServer/src/main/java/CarrotServer/controller/response/ClubGetResponse.java
  CarrotServer/src/main/java/CarrotServer/controller/response/ClubListResponseDTO.java
  CarrotServer/src/main/java/CarrotServer/domain/ClubCategory.java
  CarrotServer/src/main/java/CarrotServer/domain/Clubs.java
  CarrotServer/src/main/java/CarrotServer/domain/Lives.java
  CarrotServer/src/main/java/CarrotServer/exception/Success.java
  CarrotServer/src/main/java/CarrotServer/mapper/ClubMapper.java
  CarrotServer/src/main/java/CarrotServer/repository/ClubJpaRepository.java
  CarrotServer/src/main/java/CarrotServer/repository/LifeJpaRepository.java
  CarrotServer/src/main/java/CarrotServer/service/ClubService.java
  CarrotServer/src/main/java/CarrotServer/service/LifeService.java
Labels: euna, FEAT

#18 [REFACTOR] 도메인 클래스명 수정
  CarrotServer/src/main/java/CarrotServer/controller/request/ProfileCreateRequest.java
  CarrotServer/src/main/java/CarrotServer/controller/response/AlbumGetResposne.java
  CarrotServer/src/main/java/CarrotServer/controller/response/ClubGetResponse.java
  CarrotServer/src/main/java/CarrotServer/domain/Album.java
  CarrotServer/src/main/java/CarrotServer/domain/Club.java
  CarrotServer/src/main/java/CarrotServer/domain/Life.java
  CarrotServer/src/main/java/CarrotServer/domain/Profile.java
  CarrotServer/src/main/java/CarrotServer/mapper/ClubMapper.java
  CarrotServer/src/main/java/CarrotServer/mapper/LifeMapper.java
  CarrotServer/src/main/java/CarrotServer/repository/ClubJpaRepository.java
  CarrotServer/src/main/java/CarrotServer/repository/LifeJpaRepository.java
  CarrotServer/src/main/java/CarrotServer/repository/ProfileJpaRepository.java
  CarrotServer/src/main/java/CarrotServer/service/ClubService.java
  CarrotServer/src/main/java/CarrotServer/service/LifeService.java
  CarrotServer/src/main/java/CarrotServer/service/ProfileService.java
Labels: euna, REFACTOR

#20 [CHORE] 더미 이미지 생성
  img/.DS_Store
  img/albums/.DS_Store
  img/albums/배드민턴 1.png
  img/albums/배드민턴 2.png
  img/albums/배드민턴 3.png
  img/albums/배드민턴 4.png
  img/albums/배드민턴 5.png
  img/club_background/.DS_Store
  img/club_background/배드민턴.png
  img/club_main/.DS_Store
  img/club_main/가족캠핑.png
  img/club_main/강아지가족.png
  img/club_main/골프.png
  img/club_main/광교새댁.png
  img/club_main/나는냐옹.png
  img/club_main/디자이너_개발자.png
  img/club_main/반려동물가족모임.png
  img/club_main/배드민턴.png
  img/club_main/블로그.png
  img/club_main/사주보기.png
  img/club_main/영어회화.png
  img/club_main/인맥사교.png
  img/club_main/저녁맥주.png
  img/club_main/테니스.png
  img/club_main/토끼키우기.png
  img/club_participants/.DS_Store
  img/club_participants/가족캠핑.png
  img/club_participants/강아지가족.png
  img/club_participants/광교새댁.png
  img/club_participants/나는냐옹.png
  img/club_participants/디자이너_개발자.png
  img/club_participants/반려동물가족모임.png
  img/club_participants/배드민턴.png
  img/club_participants/블로그.png
  img/club_participants/사주보기.png
  img/club_participants/스크린골프.png
  img/club_participants/영어회화.png
  img/club_participants/인맥사교.png
  img/club_participants/저녁맥주.png
  img/club_participants/테니스.png
  img/club_participants/토끼키우기.png
Labels: euna

#23 [FEAT] 본인이 개발한 API에 Swagger 설정
  CarrotServer/build.gradle
  CarrotServer/src/main/java/CarrotServer/common/swagger/SwaggerConfig.java
  CarrotServer/src/main/java/CarrotServer/controller/ClubController.java
  CarrotServer/src/main/java/CarrotServer/controller/LifeController.java
  CarrotServer/src/main/java/CarrotServer/controller/response/ClubListResponseDTO.java
  CarrotServer/src/main/java/CarrotServer/controller/response/ClubResponseDTO.java
  CarrotServer/src/main/java/CarrotServer/controller/response/LifeListResponseDTO.java
  CarrotServer/src/main/java/CarrotServer/controller/response/LifeResponseDTO.java
  CarrotServer/src/main/java/CarrotServer/mapper/ClubMapper.java
  CarrotServer/src/main/java/CarrotServer/mapper/LifeMapper.java
  CarrotServer/src/main/java/CarrotServer/service/ClubService.java
  CarrotServer/src/main/java/CarrotServer/service/LifeService.java
Labels: euna, FEAT

#24 [FEAT] Swagger 코드 추가
  CarrotServer/src/main/java/CarrotServer/controller/ClubController.java
  CarrotServer/src/main/java/CarrotServer/exception/Success.java
Labels: FEAT, 2.or_kng

#26 [REFACTOR] DTO 클래스 명 수정
  CarrotServer/src/main/java/CarrotServer/controller/ClubController.java
  CarrotServer/src/main/java/CarrotServer/controller/request/ProfileRequestDTO.java
  CarrotServer/src/main/java/CarrotServer/controller/response/AlbumResposneDTO.java
  CarrotServer/src/main/java/CarrotServer/controller/response/ClubDetailResponseDTO.java
  CarrotServer/src/main/java/CarrotServer/service/ClubService.java
  CarrotServer/src/main/java/CarrotServer/service/ProfileService.java
Labels: 2.or_kng, REFACTOR

#28 [FEAT] Error Handling
  CarrotServer/src/main/java/CarrotServer/common/response/ApiResponse.java
  CarrotServer/src/main/java/CarrotServer/controller/ClubController.java
  CarrotServer/src/main/java/CarrotServer/controller/LifeController.java
  CarrotServer/src/main/java/CarrotServer/exception/GlobalExceptionHandler.java
  CarrotServer/src/main/java/CarrotServer/exception/enums/Error.java
  CarrotServer/src/main/java/CarrotServer/exception/enums/Success.java
  CarrotServer/src/main/java/CarrotServer/exception/model/CarrotException.java
  CarrotServer/src/main/java/CarrotServer/service/ClubService.java
Labels: euna, FEAT

#30 [REFACTOR] CustomError 핸들링 코드 클래스 네이밍 수정 및 메서드 네이밍 수정
  CarrotServer/src/main/java/CarrotServer/exception/CustomExceptionHandler.java
Labels: euna
